# Generated by Django 5.1.3 on 2024-11-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redactor',
            options={'verbose_name': 'Redactor', 'verbose_name_plural': 'Redactors'},
        ),
        migrations.RemoveField(
            model_name='redactor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='redactor',
            name='years_of_experience',
        ),
    ]
