# Generated by Django 5.1.3 on 2024-12-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_newspaper_published_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="published_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
